### ISSUE TITLE
进入文章界面点击右上角菜单展开再收缩就卡住了

### ISSUE THREAD

**Issue by mhxak** [wee-design/Mix#3]
如图，展开再收缩屏幕就变暗了，什么都点不了了。
![Screenshot_2021-05-10-23-14-16-432_com android browser](https://user-images.githubusercontent.com/83968810/117682605-dbfe4c80-b178-11eb-841b-1f55b3ce8ccb.jpg)
![Screenshot_2021-05-10-23-14-27-756_com android browser](https://user-images.githubusercontent.com/83968810/117682658-e91b3b80-b178-11eb-99bf-8a8d5137556c.jpg)
![Screenshot_2021-05-10-23-15-14-511_com android browser](https://user-images.githubusercontent.com/83968810/117682697-f33d3a00-b178-11eb-95c6-6b1b03fe25b2.jpg)

**Comment by mhxak** [comment]
我发个中文显得多么格格不入。︿(￣︶￣)︿

**Comment by wibus-wee** [comment]
在最新版本已经修复啦
